spring.application.name=6-github-actions

# Connection
spring.datasource.url=jdbc:mysql://localhost:3306/compactdisc
spring.datasource.username=root
spring.datasource.password=

# Schema generation
spring.jpa.hibernate.ddl-auto=update

# Hibernate extras
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
